### ISSUE TITLE
process_fcs() : Error 'x' must be an object of class flowFrame

### ISSUE THREAD

**Issue by ppreshant** [ucl-cssb/flopr#8]
I'm trying to use flopR to analyze a few .fcs files for the automated features it provides. I have installed the package using `devtools::install_github()` and ensured the prerequisites `c("flowCore", "flowClust", "flowStats")` are installed. 

When I try to run one .fcs file at a time from the dataset using `process_fcs(_fcspath_, flu_channels = 'mScarlet-I-A', do_plot = T)`

 I get the output - 
```
[1] "2 clusters found"
[1] "only debris found"
Error 'x' must be an object of class flowFrame
```
and some additional warning messages reg NaNs and fluorescent channel exceeding saturation

How do I go about troubleshooting this since no additional information is given about the function generating the error? 

I am able to read and visualize the same files using flowWorkspace::'s cytoset and cytoframe datatypes like this - 
![image](https://user-images.githubusercontent.com/14856479/163466524-5795a1ec-0a0a-459a-a546-408cfa89ed42.png)

The .fcs file is attached here - 
[E01.zip](https://github.com/ucl-cssb/flopr/files/8491964/E01.zip)

**Desktop:**
 - OS: Windows 10
 - R Version : 4.1

**Comment by ajfedorec** [comment]
Thanks for bring this to my attention. The error was due to the way I was handling "debris". I've now removed the "debris only" classification as it was just based on some hardcoded thresholds which weren't universally relevant.

Can you reinstall flopr with devtools::install_github('ucl-cssb/flopr') and try again?

Thanks for your patience
